name: ChestUI
description: ChestUI
version: 3.1
author: hazae41
main: hazae41.chestui.Main
api-version: 1.16
softdepend: [ Kotlin ]

commands:
  chestui:
    permission: chestui.op
    description: ChestUI

permissions:
  'chestui.op':
    default: op